### ISSUE TITLE
占用点击事件

### ISSUE THREAD

**Issue by wangxp423** [msandroid/MultiShapeView#1]
首先非常感谢作者的这个Demo
实际应用中发现当给这个View setOnClickListener的时候。点击事件被View里面的OnTouchEvent给占用了
当我把他注释掉的时候，发现不影响点击蒙层效果。
再次感谢作者的demo

**Comment by msandroid** [comment]
onTouchEvent()中并没有对Action做特殊处理, 所以和onClick()并不会发生冲突，我没明白你说的占用是什么意思？

**Comment by CatTalk2** [comment]
@wangxp423 
onTouchEvent()中并没有对Action做特殊处理, 所以和onClick()并不会发生冲突，我没明白你说的占用是什么意思？

**Comment by wangxp423** [comment]
就是我给这个view添加点击事件，但是点击事件无效

**Comment by zxhi** [comment]
对的我也是添加点击事件无效，onTouchEvent()注销掉就好了并不影响点击蒙层效果

**Comment by CatTalk2** [comment]
已修复，无需覆写onTouchEvent()
